# Generated by Django 6.0.7 on 2026-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='media_type',
            field=models.CharField(default='image', max_length=10),
        ),
    ]
