# Generated by Django 6.0.7 on 2026-08-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrS', '0002_qrcode_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='file',
            field=models.URLField(),
        ),
    ]
